apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
      - port: 80
        #targetPort: 80 -> se eu não declarar o targetPort ele assume o mesmo valor do port
        nodePort: 30000
  selector:
    app: primeiro-pod