apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticas
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort-> quando não colocamos ele coloca o mesmo do port 80
      nodePort: 30000
  selector:
    app: portal-noticias